### ISSUE TITLE
Despliegue de una meta seleccionada

### ISSUE THREAD

**Issue by ChristopherObando** [jose-andres-ucr/nutrimetas#21]
**Yo como paciente** o **como profesional de salud**
**Quiero** seleccionar de una lista de metas **una meta**
**Para** ver los detalles de la meta seleccionada

Tareas Técnicas

- Crear query para obtener detalles de una meta específica

  - [x] Acceder a la base de datos y obtener la información completa de una meta específica utilizando su ID.
  - [x] Implementar la query en el backend para que se pueda llamar desde el frontend.

- Definir qué campos se mostrarán y cómo se mostrarán

  - [x] Determinar los campos que se deben mostrar en la pantalla de detalles de la meta (por ejemplo, nombre de la meta, descripción, fecha de creación, etc.).
  - [x] Decidir la forma de mostrar cada campo (por ejemplo, dropdown para estados, campos de texto para nombres y descripciones, etc.).

- Crear pantalla para despliegue de información de una meta específica

  - [x] Diseñar la interfaz de usuario para mostrar los detalles de la meta seleccionada.
  - [x] Implementar la interfaz en el frontend, integrando los datos obtenidos de la base de datos.

Criterios de aceptación

- Poseer una pantalla para observar la meta seleccionada
- La pantalla debe mostrar todos los detalles de la meta recién seleccionada.
- La pantalla debe mostrar los comentarios de esa meta seleccionada
