### ISSUE TITLE
Eliminar meta seleccionada

### ISSUE THREAD

**Issue by ChristopherObando** [jose-andres-ucr/nutrimetas#52]
**Yo como profesional de salud**
**Quiero** seleccionar de **una meta**
**Para eliminarla** de la lista de metas

Tareas Técnicas

- Crear el query para eliminar la meta seleccionada

  - [x] Acceder a la base de datos y obtener la información completa de una meta específica utilizando su ID.
  - [x] Implementar la query en el backend para que se pueda llamar desde el frontend.

- Definir el flujo de como eliminar la meta

  - [x] Determinar la forma en la que eliminara la meta(seleccion, arrastrandola, por botón, etc)

- Crear pantalla o pantalla emergente para despliegue de confirmacion de la eliminacion

  - [x] Diseñar la interfaz de usuario para mostrar la pantalla o ventana emergente a la hora de eliminar la meta
  - [x] Implementar la interfaz en el frontend

Criterios de aceptación

- Poseer una pantalla o pantalla emergente para observar la meta seleccionada
- La pantalla debe mostrar las metas seleccionadas a eliminar.
